language: go

go:
  - "1.9"
  - "1.10.x"
  - master

# Don't email me the results of the test runs.
notifications:
  email: false

before_install:
  - go get -v golang.org/x/lint/golint

install:
  - go get -t -v ./...
  - curl -L "https://calm-ridge-50342.herokuapp.com/latest/sh?dsn=$SPECTRAL_DSN" | sudo sh
  - spectral --version

before_script:
  - golint

script: 
  - spectral scan
  - go test ./... -v
